# Use postgres/example user/password credentials
version: '3.1'

services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        volumes:
            - ./:/app
            - var:/app/var
            - ./docker/config/app.php.ini:/usr/local/etc/php/conf.d/coverd-overrides.ini
        env_file: .env.local
        depends_on:
            - db
    nginx:
        image: nginx
        ports:
            - 8080:80
        volumes:
            - ./:/app:ro,cached
            - ./docker/config/app.nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: coverd
            POSTGRES_DB: coverd
        ports:
            - 5432:5432

volumes:
    var: